# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 50391dad3c335ea4379dacd9f5f09eeb60abe9f5ede1b0d0d42501bc299df4341f1839ca487bfcb1d8e1a2b4c65aa34e0996b8a060b36c6079f77083e7b3795b

test:
  secret_key_base: 7a1f6e7ccb9feb6283caae252b133c795bbf0ed92fcb7884624f4160223130b412e94b0e04bf452411196b4ef358b0775bde1d386a97e0ceaa7cf538b253e428

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
